# Generated by Django 4.2 on 2023-04-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
