# Generated by Django 4.2 on 2023-04-13 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_priority_task_prioriti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='prioriti',
        ),
    ]
