# Generated by Django 4.2 on 2023-04-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_remove_task_prioriti'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prio',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
