# Generated by Django 4.2 on 2023-04-13 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_task_prio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='prio',
            new_name='priority',
        ),
    ]
