# Generated by Django 4.2 on 2023-04-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_rename_prio_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1996-10-10'),
            preserve_default=False,
        ),
    ]
